<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Nhà Giả Kim',
                'author' => 'Paulo Coelho',
                'price' => 150000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/5b/24/38/5950c0d0f4f1fef8aef60b3d699a63f1.jpg',
                'is_active' => true,
                'quantity' => 100,
                'sold' => 50,
                'sale_off' => 10,
            ],
            [
                'title' => 'Đắc Nhân Tâm',
                'author' => 'Dale Carnegie',
                'price' => 120000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/2f/98/92/0f4fbb1dc1444d0d5b2d61b046e8f0d8.jpg',
                'is_active' => true,
                'quantity' => 80,
                'sold' => 40,
                'sale_off' => 5,
            ],
            [
                'title' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
                'author' => 'Rosie Nguyễn',
                'price' => 100000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/1b/11/b1/fdb12e8e037805cf869bb209c1e2a839.jpg',
                'is_active' => true,
                'quantity' => 70,
                'sold' => 30,
                'sale_off' => 0,
            ],
            [
                'title' => 'Dám Bị Ghét',
                'author' => 'Ichiro Kishimi, Fumitake Koga',
                'price' => 110000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/33/87/7d/3fae6a38a10df2b76b9f03c5d253cc41.jpg',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 25,
                'sale_off' => 0,
            ],
            [
                'title' => 'Cha Giàu Cha Nghèo',
                'author' => 'Robert T. Kiyosaki',
                'price' => 130000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/ed/7f/43/7f04f6e7d9e67c9d7e7db7f87ef9264a.jpg',
                'is_active' => true,
                'quantity' => 90,
                'sold' => 35,
                'sale_off' => 10,
            ],
            [
                'title' => 'Người Giàu Nhất Thành Babylon',
                'author' => 'George S. Clason',
                'price' => 125000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/9f/2c/1e/0b3eddd9e9db59fbe92de73b47f76f61.jpg',
                'is_active' => true,
                'quantity' => 70,
                'sold' => 20,
                'sale_off' => 5,
            ],
            [
                'title' => 'Nhà Đầu Tư Thông Minh',
                'author' => 'Benjamin Graham',
                'price' => 140000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/14/91/ff/071b2c1e82b7b7f0bce6b6f7a0e8b0e8.jpg',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 15,
                'sale_off' => 0,
            ],
            [
                'title' => 'Sức Mạnh Của Thói Quen',
                'author' => 'Charles Duhigg',
                'price' => 115000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/12/31/aa/b9b51ff0c3c99f47a7d4f0d5f9d6c5a9.jpg',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 30,
                'sale_off' => 0,
            ],
            [
                'title' => 'Tư Duy Nhanh Và Chậm',
                'author' => 'Daniel Kahneman',
                'price' => 150000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/ab/12/34/abcd1234.jpg',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 20,
                'sale_off' => 20,
            ],
            [
                'title' => 'Khi Hơi Thở Hóa Thinh Không',
                'author' => 'Paul Kalanithi',
                'price' => 135000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/ef/12/34/ef1234abcd.jpg',
                'is_active' => true,
                'quantity' => 30,
                'sold' => 10,
                'sale_off' => 0,
            ],
            [


                'title' => 'Lối Sống Tối Giản Của Người Nhật',
                'author' => 'Fumio Sasaki',
                'price' => 120000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/5f/23/45/lifestyle-minimalism.jpg',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 20,
                'sale_off' => 0,
            ],
            [
                'title' => 'Đừng Bao Giờ Đi Ăn Một Mình',
                'author' => 'Keith Ferrazzi',
                'price' => 110000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/6a/24/78/networking.jpg',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 25,
                'sale_off' => 5,
            ],
            [
                'title' => 'Chiến Thắng Con Quỷ Trong Ta',
                'author' => 'Stephen Pressfield',
                'price' => 115000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/7b/32/90/overcoming-resistance.jpg',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 10,
                'sale_off' => 0,
            ],
            [
                'title' => 'Dám Thất Bại',
                'author' => 'Fumio Sasaki',
                'price' => 105000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/8c/21/65/fail-forward.jpg',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 15,
                'sale_off' => 0,
            ],
            [
                'title' => 'Nghệ Thuật Đọc Vị Bất Kỳ Ai',
                'author' => 'Henrik Fexeus',
                'price' => 125000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/9d/43/77/reading-people.jpg',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 20,
                'sale_off' => 0,
            ],
            [
                'title' => 'Người Nam Châm',
                'author' => 'Leila L.',
                'price' => 95000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/0e/32/88/magnet-person.jpg',
                'is_active' => true,
                'quantity' => 30,
                'sold' => 10,
                'sale_off' => 0,
            ],
            [
                'title' => 'Đời Ngắn Đừng Ngủ Dài',
                'author' => 'Robin Sharma',
                'price' => 115000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/1f/54/99/short-life.jpg',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 30,
                'sale_off' => 5,
            ],
            [
                'title' => 'Bí Mật Tư Duy Triệu Phú',
                'author' => 'T. Harv Eker',
                'price' => 120000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/2g/65/11/secret-millionaire.jpg',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 20,
                'sale_off' => 0,
            ],
            [
                'title' => 'Những Bức Di Thư Thành Cổ',
                'author' => 'Luân Vũ',
                'price' => 90000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/3h/76/22/ancient-letters.jpg',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 15,
                'sale_off' => 0,
            ],
            [
                'title' => 'Kính Vạn Hoa',
                'author' => 'Nguyễn Nhật Ánh',
                'price' => 95000,
                'thumbnail' => 'https://salt.tikicdn.com/cache/400x400/ts/product/4i/87/33/kinh-van-hoa.jpg',
                'is_active' => true,
                'quantity' => 100,
                'sold' => 50,
                'sale_off' => 0,
            ],
        ];

        foreach ($books as $bookData) {
            Book::create($bookData);
        }
    }
}
