<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Nhà Giả Kim',
                'author' => 'Paulo Coelho',
                'price' => 150000,
                'thumbnail' => '/storage/BookImages/Thumbnail_1_20251008_162405.jpg',
                'is_active' => true,
                'quantity' => 100,
                'sold' => 150,
                'sale_off' => 10,
            ],
            [
                'title' => 'Đắc Nhân Tâm',
                'author' => 'Dale Carnegie',
                'price' => 120000,
                'thumbnail' => '/storage/BookImages/Thumbnail_2_20251008_132354.webp',
                'is_active' => true,
                'quantity' => 80,
                'sold' => 140,
                'sale_off' => 5,
            ],
            [
                'title' => 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
                'author' => 'Rosie Nguyễn',
                'price' => 100000,
                'thumbnail' => '/storage/BookImages/Thumbnail_3_20251008_131507.jpeg',
                'is_active' => true,
                'quantity' => 70,
                'sold' => 430,
                'sale_off' => 0,
            ],
            [
                'title' => 'Dám Bị Ghét',
                'author' => 'Ichiro Kishimi, Fumitake Koga',
                'price' => 110000,
                'thumbnail' => '/storage/BookImages/Thumbnail_4_20251008_132500.webp',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 75,
                'sale_off' => 0,
            ],
            [
                'title' => 'Cha Giàu Cha Nghèo',
                'author' => 'Robert T. Kiyosaki',
                'price' => 130000,
                'thumbnail' => '/storage/BookImages/Thumbnail_5_20251008_162224.jpg',
                'is_active' => true,
                'quantity' => 90,
                'sold' => 135,
                'sale_off' => 10,
            ],
            [
                'title' => 'Người Giàu Nhất Thành Babylon',
                'author' => 'George S. Clason',
                'price' => 125000,
                'thumbnail' => '/storage/BookImages/Thumbnail_6_20251008_135828.webp',
                'is_active' => true,
                'quantity' => 70,
                'sold' => 120,
                'sale_off' => 5,
            ],
            [
                'title' => 'Nhà Đầu Tư Thông Minh',
                'author' => 'Benjamin Graham',
                'price' => 140000,
                'thumbnail' => '/storage/BookImages/Thumbnail_7_20251008_131932.jpg',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 115,
                'sale_off' => 0,
            ],
            [
                'title' => 'Sức Mạnh Của Thói Quen',
                'author' => 'Charles Duhigg',
                'price' => 115000,
                'thumbnail' => '/storage/BookImages/Thumbnail_8_20251008_132819.webp',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 330,
                'sale_off' => 0,
            ],
            [
                'title' => 'Tư Duy Nhanh Và Chậm',
                'author' => 'Daniel Kahneman',
                'price' => 150000,
                'thumbnail' => '/storage/BookImages/Thumbnail_9_20251008_101102.webp',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 620,
                'sale_off' => 20,
            ],
            [
                'title' => 'Khi Hơi Thở Hóa Thinh Không',
                'author' => 'Paul Kalanithi',
                'price' => 135000,
                'thumbnail' => '/storage/BookImages/Thumbnail_10_20251008_140531.webp',
                'is_active' => true,
                'quantity' => 30,
                'sold' => 110,
                'sale_off' => 0,
            ],
            [
                'title' => 'Lối Sống Tối Giản Của Người Nhật',
                'author' => 'Fumio Sasaki',
                'price' => 120000,
                'thumbnail' => '/storage/BookImages/Thumbnail_11_20251008_135938.webp',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 120,
                'sale_off' => 0,
            ],
            [
                'title' => 'Đừng Bao Giờ Đi Ăn Một Mình',
                'author' => 'Keith Ferrazzi',
                'price' => 110000,
                'thumbnail' => '/storage/BookImages/Thumbnail_12_20251008_135650.webp',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 245,
                'sale_off' => 5,
            ],
            [
                'title' => 'Chiến Thắng Con Quỷ Trong Ta',
                'author' => 'Stephen Pressfield',
                'price' => 115000,
                'thumbnail' => '/storage/BookImages/Thumbnail_13_20251008_141716.webp',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 660,
                'sale_off' => 0,
            ],
            [
                'title' => 'Dám Thất Bại',
                'author' => 'Fumio Sasaki',
                'price' => 105000,
                'thumbnail' => '/storage/BookImages/Thumbnail_14_20251008_140252.jpg',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 125,
                'sale_off' => 0,
            ],
            [
                'title' => 'Nghệ Thuật Đọc Vị Bất Kỳ Ai',
                'author' => 'Henrik Fexeus',
                'price' => 125000,
                'thumbnail' => '/storage/BookImages/Thumbnail_15_20251008_141514.webp',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 120,
                'sale_off' => 0,
            ],
            [
                'title' => 'Người Nam Châm',
                'author' => 'Leila L.',
                'price' => 95000,
                'thumbnail' => '/storage/BookImages/Thumbnail_16_20251008_141347.webp',
                'is_active' => true,
                'quantity' => 30,
                'sold' => 120,
                'sale_off' => 0,
            ],
            [
                'title' => 'Đời Ngắn Đừng Ngủ Dài',
                'author' => 'Robin Sharma',
                'price' => 115000,
                'thumbnail' => '/storage/BookImages/Thumbnail_17_20251008_135545.webp',
                'is_active' => true,
                'quantity' => 60,
                'sold' => 360,
                'sale_off' => 5,
            ],
            [
                'title' => 'Bí Mật Tư Duy Triệu Phú',
                'author' => 'T. Harv Eker',
                'price' => 120000,
                'thumbnail' => '/storage/BookImages/Thumbnail_18_20251008_141245.webp',
                'is_active' => true,
                'quantity' => 50,
                'sold' => 260,
                'sale_off' => 0,
            ],
            [
                'title' => 'Những Bức Di Thư Thành Cổ',
                'author' => 'Luân Vũ',
                'price' => 90000,
                'thumbnail' => '/storage/BookImages/Thumbnail_19_20251008_140423.webp',
                'is_active' => true,
                'quantity' => 40,
                'sold' => 115,
                'sale_off' => 0,
            ],
            [
                'title' => 'Kính Vạn Hoa',
                'author' => 'Nguyễn Nhật Ánh',
                'price' => 95000,
                'thumbnail' => '/storage/BookImages/Thumbnail_20_20251008_132638.webp',
                'is_active' => true,
                'quantity' => 100,
                'sold' => 150,
                'sale_off' => 0,
            ],
        ];

        foreach ($books as $bookData) {
            Book::create($bookData);
        }
    }
}
